Issue 687 - add more fission test results
mozilla-frontend-infra/firefox-health-dashboard pull request #705
Opened 2020-07-01 12:21 UTC by airimovici

2020-07-01 12:21 UTC, airimovici commented
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/687

2020-08-27 15:24 UTC, davehunt requested changes
The code changes look good, but I notice that the deploy review is failing to show any data on the Fission page. I've also added some suggestions to make the names/labels more consistent.

2020-08-27 15:24 UTC, davehunt commented on src/fission/config.js
> +    ['sessionrestore_many_windows', 'Sessionrestore many windows', 'sessionrestore_many_windows'],
```suggestion
    ['start-up-(sessionrestore_many_windows)', 'Start-up (sessionrestore_many_windows)', 'sessionrestore_many_windows'],
```

2020-08-27 15:24 UTC, davehunt commented on src/fission/config.js
> +    ['startup_about_home_paint', 'Startup about home paint', 'startup_about_home_paint'],
```suggestion
    ['start-up-(about_home_paint)', 'Start-up (about_home_paint)', 'startup_about_home_paint'],
```

2020-08-27 15:24 UTC, davehunt commented on src/fission/config.js
>      ['start-up-(ts_paint)', 'Start-Up (ts_paint)', 'ts_paint'],
```suggestion
    ['start-up-(ts_paint)', 'Start-up (ts_paint)', 'ts_paint'],
```

2020-08-27 15:24 UTC, davehunt commented on src/fission/config.js
> +    ['startup_about_home_paint_realworld_webextensions', 'Startup about home paint realworld webextensions', 'startup_about_home_paint_realworld_webextensions'],
```suggestion
    ['start-up-(about_home_paint_realworld_webextensions)', 'Start-up (about_home_paint_realworld_webextensions)', 'startup_about_home_paint_realworld_webextensions'],
```

2020-09-01 08:25 UTC, davehunt approved these changes

2020-09-01 08:25 UTC, merged